#!/bin/bash
clear
rm -rf ~/NetBeansProjects/bscthesis2/src/main/java/ir/ac/ut/snl/mrcd/stagefourtmp
rm -rf ~/NetBeansProjects/bscthesis2/output/stagefour
rm stagefour.jar
mkdir ~/NetBeansProjects/bscthesis2/src/main/java/ir/ac/ut/snl/mrcd/stagefourtmp
javac -classpath ~/Downloads/hadoop-1.2.1/hadoop-core-1.2.1.jar:commons-lang3-3.3.2.jar *.java -d ~/NetBeansProjects/bscthesis2/src/main/java/ir/ac/ut/snl/mrcd/stagefourtmp
jar -cvf stagefour.jar -C ~/NetBeansProjects/bscthesis2/src/main/java/ir/ac/ut/snl/mrcd/stagefourtmp .
~/Downloads/hadoop-1.2.1/bin/hadoop jar stagefour.jar ir.ac.ut.snl.mrcd.StageFour ~/NetBeansProjects/bscthesis2/output/stagetwo ~/NetBeansProjects/bscthesis2/output/stagefour
